[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
allowed_paths = ["./broadcast"]
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
  '@solmate=lib/solmate/src/',
  'foundry-devops=lib/foundry-devops'
]
